{"name": "Verify login functionality", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'sauce_username.txt'", "trace": "self = <test_saucedemo_ui.TestSaucedemo.TestUserAuthentication object at 0x10ab1c0d0>, start_sauce_instance = <modules.ui.page_objects.saucedemo.StartSaucedemo object at 0x10ab1cd60>\n\n    @allure.title(\"Verify login functionality\")\n    @pytest.mark.sauce\n    def test_login(self, start_sauce_instance):\n>       with open(\"sauce_username.txt\", \"r\") as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'sauce_username.txt'\n\ntests/ui/test_saucedemo_ui.py:15: FileNotFoundError"}, "start": 1707771726290, "stop": 1707771726291, "uuid": "51ad113a-b961-4ed9-9dc9-a90635a6e924", "historyId": "65e85a0bccfe9ecdd1292c20722f1f9f", "testCaseId": "65e85a0bccfe9ecdd1292c20722f1f9f", "fullName": "tests.ui.test_saucedemo_ui.TestUserAuthentication#test_login", "labels": [{"name": "feature", "value": "User Authentication"}, {"name": "suite", "value": "Saucedemo"}, {"name": "tag", "value": "sauce"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "subSuite", "value": "TestSaucedemo"}, {"name": "host", "value": "EPUAVINW0156"}, {"name": "thread", "value": "25918-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_saucedemo_ui"}]}